# fly.toml app configuration file generated for face-recognition-app on 2024-06-20T23:12:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'face-recognition-app'
primary_region = 'mad'

[build]
  dockerfile = "./Face-Recognition-Server/Dockerfile"

[http_service]
  internal_port = 5000
  force_https = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
